version: '3.7'

services:

  mydb:
    image: mysql:5.7.25
    restart: on-failure
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=blog123.
    networks:
      - blog-net

  php-fpm:
    build: ./php-fpm
    volumes:
      - ./blog:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mydb
    networks:
      - blog-net

networks:
  blog-net: