version: '3.7'

services:

  mydb:
    image: mysql:5.7.25
    restart: on-failure
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=blog123.
    networks:
      - blog-net

  php-fpm:
    build: ./php-fpm
    volumes:
      - ./website:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - mydb
    networks:
      - blog-net

  nginx:
    image: nginx:1.15.9
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/vhost:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx
      - ./website:/usr/share/nginx/html
    environment:
      - "TZ=Asia/Shanghai"
    depends_on:
      - php-fpm
    networks:
      - blog-net

networks:
  blog-net: